### ISSUE TITLE
PRE-01: DAFO ONG

### ISSUE THREAD

**Issue by pabpercab1** [ISPP-G5/Organization#1]

**Comment by Ahydul** [comment]
@claugp06 el DAFO de ayudando a crecer está bastante bien. Sólo dos detalles:

1. En la fortaleza del ideario cristiano, en mi opinión se trata más bien de una fortaleza porque atrae a las familias cristianas que quieren educar sus hijos con sus valores, es decir, podrías aclarar que la fortaleza es atraer dichas familias.

2. También es una amenaza dicho ideario porque en los últimos años hay una tendencia de que cada vez hay menos cristianos y las familias jóvenes (cada vez menos cristianas) pueden no querer identificarse con algo religiosos independientemente de sus otras cualidades.

Solo dos tonterías, por lo demás esta perfecto!

**Comment by claugp06** [comment]
Vale, gracias. Lo añado sin problema.

**Comment by Ahydul** [comment]
Los DAFOs están bastante bien. Lo único que veo que habría que cambiar es en la fortaleza de Manos Abiertas "No religiosa". Se siente como una comparación directa a la otra ONG. Más que una fortaleza, es que no tiene esa posible debilidad (de exclusividad). Una posible fortaleza es que presentan numerosas actividades: campamento de verano, escuela de verano, etc.
