### ISSUE TITLE
Refinar idea clave de negocio

### ISSUE THREAD

**Issue by MRomalde** [ISPP-G5/Organization#16]

**Comment by fracalrod3** [comment]
La cuestión es que los usuarios como profesores, administradores y familiares sí pueden acceder, y los alumnos no son usuarios de la plataforma como tal, o eso he entendido yo

________________________________
De: Ahydul ***@***.***>
Enviado: sábado, 10 de febrero de 2024 17:27
Para: ISPP-G5/Organization ***@***.***>
Cc: FRANCISCO JAVIER CALDERÓN RODRÍGUEZ ***@***.***>; Assign ***@***.***>
Asunto: Re: [ISPP-G5/Organization] Refinar idea clave de negocio (Issue #16)


Buenas, estoy revisando el documento y hay una parte que, según he entendido yo los requisitos, creo que no es correcta.

"Este proyecto permitirá a los usuarios darse de alta para acceder a los cursos"

En los requisitos entiendo yo que los usuarios no se dan de alta si no que el administrador crea los usuarios y luego estos podrán iniciar sesión.

**Comment by Ahydul** [comment]
He visto el nuevo documento y lo veo bien
